"""
Company-Specific Interview Questions
Curated questions for major tech companies across different categories
Expanded to 20+ questions per category for comprehensive preparation
"""

# Import mass recruitment questions
try:
    from services.mass_recruitment_questions import MASS_RECRUITMENT_QUESTIONS
except ImportError:
    MASS_RECRUITMENT_QUESTIONS = {}

COMPANY_QUESTIONS = {
    "Google": {
        "Python": [
            "How would you use Python for Google's search infrastructure?",
            "Explain how you'd develop Python services for Google Cloud Platform.",
            "How would you implement Python APIs for Google's products?",
            "What's your approach to Python development for YouTube's backend?",
            "How would you use Python for Google's ML infrastructure?",
            "Explain how you'd build Python tools for Google's data processing.",
            "How would you implement Python services for Google Maps?",
            "What's your approach to Python testing at Google scale?",
            "How would you use Python with Google's BigQuery?",
            "Explain how you'd optimize Python for billions of queries.",
            "How would you implement Python microservices on Google Kubernetes Engine?",
            "What's your approach to Python development for Android services?",
            "How would you use Python for Google's advertising platform?",
            "Explain how you'd build Python automation for Google Workspace.",
            "How would you implement Python-based data pipelines on Google Cloud?",
            "What's your approach to Python development for Chrome services?",
            "How would you use Python with Google's AI/ML services?",
            "Explain how you'd optimize Python for Google's distributed systems.",
            "How would you implement Python tools for Google Analytics?",
            "What's your approach to Python security in Google's infrastructure?",
        ],
        "Web Development": [
            "How would you design a web application using Google App Engine?",
            "Explain how you'd implement authentication with Google Identity Platform.",
            "How would you build a web app integrated with Google Workspace?",
            "What's your approach to developing Progressive Web Apps for Chrome?",
            "How would you design a web service using Google Cloud Endpoints?",
            "Explain how you'd implement real-time features with Firebase.",
            "How would you optimize web performance using Google's tools?",
            "What's your approach to building web apps with Material Design?",
            "How would you implement Google Sign-In in web applications?",
            "Explain how you'd design a web app with Google Cloud Load Balancing.",
        ],
        "Data Structures": [
            "How would you design data structures for Google Search indexing?",
            "Explain how you'd optimize data structures for BigQuery.",
            "What data structures would you use for Google Maps routing?",
            "How would you design caching structures for YouTube?",
            "Explain how you'd implement data structures for Gmail.",
            "How would you handle data structures for billions of searches?",
            "What's your approach to designing structures for Google Drive?",
            "How would you optimize data structures for Android performance?",
            "Explain how you'd design structures for Google's recommendation systems.",
            "How would you implement efficient indexing for Google Search?",
        ],
        "Behavioral": [
            "Why do you want to work at Google?",
            "How do you align with Google's mission to organize world's information?",
            "Tell me about a time you demonstrated Googleyness.",
            "How would you contribute to Google's innovative culture?",
            "Describe how you've worked on large-scale systems.",
            "How do you approach solving ambiguous problems?",
            "Tell me about a time you made data-driven decisions.",
            "How do you practice continuous learning and growth?",
            "Describe your experience with Google's technologies.",
            "How would you handle working across multiple Google products?",
        ],
        "System Design": [
            "How would you design Google Search's crawling system?",
            "Explain how you'd design YouTube's video streaming infrastructure.",
            "How would you design Gmail's email storage system?",
            "Design a system like Google Maps' real-time traffic.",
            "How would you design Google Drive's file synchronization?",
            "Explain how you'd design Google's advertising auction system.",
            "How would you design a system like Google Photos?",
            "Design Google's distributed file system.",
            "How would you design Google's authentication system?",
            "Explain how you'd design Android's app distribution system.",
        ],
        "Machine Learning": [
            "How would you implement ML for Google Search ranking?",
            "Explain how you'd design ML pipelines for YouTube recommendations.",
            "How would you approach ML for Google's ad targeting?",
            "What's your approach to ML for Google Photos organization?",
            "How would you design ML systems for Google Assistant?",
            "Explain how you'd implement computer vision for Google Lens.",
            "How would you approach NLP for Google Translate?",
            "What's your approach to ML model deployment on Google Cloud?",
            "How would you design ML for Gmail's spam detection?",
            "Explain how you'd implement ML for Google's autonomous vehicles.",
        ]
    },
    "Amazon": {
        "Python": [
            "How would you use Python for Amazon's e-commerce platform?",
            "Explain how you'd develop Python services for AWS.",
            "How would you implement Python APIs for Amazon's marketplace?",
            "What's your approach to Python development for Prime Video?",
            "How would you use Python for Amazon's recommendation engine?",
            "Explain how you'd build Python tools for AWS Lambda.",
            "How would you implement Python services for Alexa?",
            "What's your approach to Python testing for Amazon's scale?",
            "How would you use Python with Amazon's data infrastructure?",
            "Explain how you'd optimize Python for millions of transactions.",
            "How would you implement Python microservices on AWS ECS?",
            "What's your approach to Python development for Kindle services?",
            "How would you use Python for Amazon's logistics systems?",
            "Explain how you'd build Python automation for AWS operations.",
            "How would you implement Python-based data processing on AWS?",
            "What's your approach to Python development for Amazon Music?",
            "How would you use Python with Amazon's ML services?",
            "Explain how you'd optimize Python for Amazon's fulfillment centers.",
            "How would you implement Python tools for AWS monitoring?",
            "What's your approach to Python security in AWS environments?",
        ],
        "Web Development": [
            "How would you design a web application using AWS services?",
            "Explain how you'd implement Amazon's product page.",
            "How would you build a web app integrated with AWS Cognito?",
            "What's your approach to developing for Amazon's marketplace?",
            "How would you design a web service using AWS API Gateway?",
            "Explain how you'd implement real-time features with AWS AppSync.",
            "How would you optimize web performance using CloudFront?",
            "What's your approach to building serverless web apps on AWS?",
            "How would you implement Amazon Pay in web applications?",
            "Explain how you'd design a web app with AWS Amplify.",
        ],
        "Data Structures": [
            "How would you design data structures for Amazon's product catalog?",
            "Explain how you'd optimize data structures for DynamoDB.",
            "What data structures would you use for Amazon's recommendation system?",
            "How would you design caching structures for Amazon's website?",
            "Explain how you'd implement data structures for order processing.",
            "How would you handle data structures for millions of products?",
            "What's your approach to designing structures for Amazon's search?",
            "How would you optimize data structures for Prime delivery routing?",
            "Explain how you'd design structures for Amazon's inventory system.",
            "How would you implement efficient product search and filtering?",
        ],
        "Behavioral": [
            "Why do you want to work at Amazon?",
            "How do you demonstrate Amazon's Leadership Principles?",
            "Tell me about a time you showed customer obsession.",
            "How would you contribute to Amazon's culture of innovation?",
            "Describe how you've delivered results under pressure.",
            "How do you approach diving deep into problems?",
            "Tell me about a time you disagreed and committed.",
            "How do you practice frugality in your work?",
            "Describe your experience with Amazon's technologies.",
            "How would you handle working on high-impact Amazon projects?",
        ],
        "System Design": [
            "How would you design Amazon's order processing system?",
            "Explain how you'd design Prime Video's streaming infrastructure.",
            "How would you design Amazon's recommendation engine?",
            "Design a system like Amazon's shopping cart.",
            "How would you design Amazon's inventory management system?",
            "Explain how you'd design Alexa's voice processing system.",
            "How would you design a system like Amazon Prime delivery?",
            "Design Amazon's payment processing system.",
            "How would you design Amazon's product search system?",
            "Explain how you'd design AWS's global infrastructure.",
        ],
        "Machine Learning": [
            "How would you implement ML for Amazon's product recommendations?",
            "Explain how you'd design ML pipelines for Alexa.",
            "How would you approach ML for Amazon's demand forecasting?",
            "What's your approach to ML for fraud detection on Amazon?",
            "How would you design ML systems for Prime Video recommendations?",
            "Explain how you'd implement computer vision for Amazon Go.",
            "How would you approach NLP for Alexa's understanding?",
            "What's your approach to ML model deployment on AWS?",
            "How would you design ML for Amazon's pricing optimization?",
            "Explain how you'd implement ML for Amazon's logistics routing.",
        ]
    },
    "Microsoft": {
        "Python": [
            "How would you use Python with Azure services?",
            "Explain how you'd develop Python applications for Microsoft 365.",
            "How would you integrate Python with .NET ecosystem?",
            "What's your approach to Python development for Azure Functions?",
            "How would you use Python for Microsoft's AI services?",
            "Explain how you'd build Python tools for Visual Studio Code.",
            "How would you implement Python APIs for Microsoft Teams?",
            "What's your approach to Python testing in Microsoft's CI/CD pipeline?",
            "How would you use Python with Microsoft Graph API?",
            "Explain how you'd optimize Python for Azure cloud infrastructure.",
            "How would you implement Python microservices on Azure Kubernetes?",
            "What's your approach to Python data processing with Azure Data Factory?",
            "How would you use Python for Azure Cognitive Services integration?",
            "Explain how you'd build Python automation for Azure DevOps.",
            "How would you implement Python-based Azure Logic Apps?",
            "What's your approach to Python development for Xbox services?",
            "How would you use Python with Azure Cosmos DB?",
            "Explain how you'd optimize Python for Windows performance.",
            "How would you implement Python tools for Power Platform?",
            "What's your approach to Python security in Azure environments?",
        ],
        "Web Development": [
            "How would you design a web application using Azure App Service?",
            "Explain how you'd implement authentication with Microsoft Identity Platform.",
            "How would you build a web app integrated with Microsoft 365?",
            "What's your approach to developing for Microsoft Teams?",
            "How would you design a web service using Azure API Management?",
            "Explain how you'd implement real-time features with Azure SignalR.",
            "How would you optimize web performance on Azure CDN?",
            "What's your approach to building Progressive Web Apps for Microsoft Edge?",
            "How would you implement Microsoft's Fluent Design System?",
            "Explain how you'd design a web app with Azure Active Directory integration.",
        ],
        "Data Structures": [
            "How would you design data structures for Azure Cosmos DB?",
            "Explain how you'd optimize data structures for Microsoft SQL Server.",
            "What data structures would you use for Microsoft's search services?",
            "How would you design caching structures for Azure Redis?",
            "Explain how you'd implement data structures for Microsoft Graph.",
            "How would you handle data structures for Office 365 data?",
            "What's your approach to designing structures for Azure Storage?",
            "How would you optimize data structures for Windows performance?",
            "Explain how you'd design structures for Microsoft's AI services.",
            "How would you implement efficient indexing for Azure Search?",
        ],
        "Behavioral": [
            "Why do you want to work at Microsoft?",
            "How do you align with Microsoft's mission to empower every person?",
            "Tell me about a time you demonstrated growth mindset.",
            "How would you contribute to Microsoft's inclusive culture?",
            "Describe how you've worked with diverse teams.",
            "How do you approach innovation at Microsoft scale?",
            "Tell me about a time you made customers successful.",
            "How do you practice continuous learning?",
            "Describe your experience with Microsoft technologies.",
            "How would you handle working across multiple Microsoft products?",
        ],
        "System Design": [
            "How would you design Microsoft Teams' messaging system?",
            "Explain how you'd design Azure's global infrastructure.",
            "How would you design Office 365's collaboration features?",
            "Design a system like OneDrive's file synchronization.",
            "How would you design Xbox Live's gaming platform?",
            "Explain how you'd design Microsoft's identity platform.",
            "How would you design a system like Power BI?",
            "Design Azure's serverless computing platform.",
            "How would you design Microsoft's AI services infrastructure?",
            "Explain how you'd design Windows Update system.",
        ],
        "Machine Learning": [
            "How would you implement ML models on Azure Machine Learning?",
            "Explain how you'd use Microsoft Cognitive Services.",
            "How would you design ML pipelines for Azure?",
            "What's your approach to ML for Microsoft's recommendation systems?",
            "How would you implement computer vision with Azure?",
            "Explain how you'd use ML for Microsoft Office features.",
            "How would you approach NLP for Microsoft's search?",
            "What's your approach to ML model deployment on Azure?",
            "How would you design ML systems for Xbox recommendations?",
            "Explain how you'd implement ML for Microsoft Security.",
        ]
    },
    "Meta (Facebook)": {
        "Python": [
            "How would you use Python for Meta's data infrastructure?",
            "Explain how you'd build Python services for Facebook's scale.",
            "How would you implement Python APIs for Instagram?",
            "What's your approach to Python development for WhatsApp backend?",
            "How would you use Python for Meta's ML infrastructure?",
            "Explain how you'd optimize Python for billions of users.",
            "How would you implement Python tools for Meta's developer platform?",
            "What's your approach to Python testing at Meta scale?",
            "How would you use Python for Meta's data analysis?",
            "Explain how you'd build Python services for Meta's ads platform.",
        ],
        "Web Development": [
            "How would you design a web application for billions of users?",
            "Explain how you'd implement Facebook's News Feed.",
            "How would you build real-time features for Instagram?",
            "What's your approach to developing Meta's messaging platform?",
            "How would you design the frontend for Facebook's interface?",
            "Explain how you'd implement Meta's authentication system.",
            "How would you optimize web performance for Facebook?",
            "What's your approach to building React applications at Meta?",
            "How would you implement Meta's GraphQL APIs?",
            "Explain how you'd design WhatsApp Web.",
        ],
        "Data Structures": [
            "How would you design data structures for Facebook's social graph?",
            "Explain how you'd implement Instagram's feed algorithm.",
            "What data structures would you use for WhatsApp's messaging?",
            "How would you design caching for Meta's applications?",
            "Explain how you'd implement data structures for Facebook's search.",
            "How would you handle data structures for billions of posts?",
            "What's your approach to designing structures for Meta's ads system?",
            "How would you optimize data structures for real-time updates?",
            "Explain how you'd design structures for Facebook Groups.",
            "How would you implement efficient friend recommendations?",
        ],
        "Behavioral": [
            "Why do you want to work at Meta?",
            "How do you align with Meta's mission to connect people?",
            "Tell me about a time you moved fast and broke things.",
            "How would you contribute to Meta's culture of innovation?",
            "Describe how you've built products for billions of users.",
            "How do you approach bold ideas at Meta scale?",
            "Tell me about a time you focused on impact.",
            "How do you practice being open and connected?",
            "Describe your experience with Meta's technologies.",
            "How would you handle working on multiple Meta products?",
        ],
        "System Design": [
            "How would you design Facebook's News Feed?",
            "Explain how you'd design Instagram's photo storage.",
            "How would you design WhatsApp's end-to-end encryption?",
            "Design a system like Facebook Messenger.",
            "How would you design Meta's advertising platform?",
            "Explain how you'd design Facebook's notification system.",
            "How would you design a system like Facebook Live?",
            "Design Meta's content delivery network.",
            "How would you design Facebook's friend recommendation system?",
            "Explain how you'd design Instagram Stories.",
        ],
        "Machine Learning": [
            "How would you design ML for Facebook's News Feed ranking?",
            "Explain how you'd implement Instagram's recommendation system.",
            "How would you approach ML for Meta's content moderation?",
            "What's your approach to ML for Facebook's ad targeting?",
            "How would you design ML systems for WhatsApp spam detection?",
            "Explain how you'd implement computer vision for Instagram filters.",
            "How would you approach NLP for Facebook's translation?",
            "What's your approach to ML model deployment at Meta scale?",
            "How would you design ML for Facebook's friend suggestions?",
            "Explain how you'd implement ML for Meta's VR/AR products.",
        ]
    },
    "Apple": {
        "Python": [
            "How would you use Python for Apple's backend services?",
            "Explain how you'd develop Python tools for iOS development.",
            "How would you implement Python APIs for Apple services?",
            "What's your approach to Python development for iCloud?",
            "How would you use Python for Apple's ML infrastructure?",
            "Explain how you'd build Python tools for macOS.",
            "How would you implement Python services for App Store?",
            "What's your approach to Python testing for Apple products?",
            "How would you use Python with Apple's cloud infrastructure?",
            "Explain how you'd optimize Python for Apple's ecosystem.",
        ],
        "Web Development": [
            "How would you design web services for Apple's ecosystem?",
            "Explain how you'd implement iCloud web interface.",
            "How would you build web apps for Apple devices?",
            "What's your approach to developing for Safari?",
            "How would you design Apple's web-based services?",
            "Explain how you'd implement Apple ID authentication.",
            "How would you optimize web performance for Apple devices?",
            "What's your approach to building responsive apps for iOS Safari?",
            "How would you implement Apple's design guidelines in web apps?",
            "Explain how you'd design web services for Apple Music.",
        ],
        "Data Structures": [
            "How would you design data structures for iOS applications?",
            "Explain how you'd optimize data structures for Apple devices.",
            "What data structures would you use for iCloud sync?",
            "How would you design caching for Apple's services?",
            "Explain how you'd implement data structures for App Store.",
            "How would you handle data structures for Apple Music?",
            "What's your approach to designing structures for macOS?",
            "How would you optimize data structures for iOS performance?",
            "Explain how you'd design structures for Apple's search.",
            "How would you implement efficient data sync across Apple devices?",
        ],
        "Behavioral": [
            "Why do you want to work at Apple?",
            "How do you align with Apple's focus on user experience?",
            "Tell me about a time you created something innovative.",
            "How would you contribute to Apple's culture of excellence?",
            "Describe how you've designed products with attention to detail.",
            "How do you approach privacy and security in your work?",
            "Tell me about a time you challenged the status quo.",
            "How do you practice thinking differently?",
            "Describe your experience with Apple's ecosystem.",
            "How would you handle working on confidential Apple products?",
        ],
        "System Design": [
            "How would you design iCloud's storage system?",
            "Explain how you'd design Apple Music's streaming service.",
            "How would you design the App Store's infrastructure?",
            "Design a system like iMessage.",
            "How would you design Apple's payment system (Apple Pay)?",
            "Explain how you'd design Siri's backend infrastructure.",
            "How would you design a system like FaceTime?",
            "Design Apple's device synchronization system.",
            "How would you design Apple's notification service?",
            "Explain how you'd design the Apple Watch health data system.",
        ],
        "Machine Learning": [
            "How would you implement ML for Siri's natural language processing?",
            "Explain how you'd design ML for Apple Photos face recognition.",
            "How would you approach ML for Apple Music recommendations?",
            "What's your approach to on-device ML for iOS?",
            "How would you design ML systems for Apple's health features?",
            "Explain how you'd implement ML for keyboard predictions.",
            "How would you approach ML for App Store recommendations?",
            "What's your approach to privacy-preserving ML at Apple?",
            "How would you design ML for Apple's camera features?",
            "Explain how you'd implement ML for fraud detection in Apple Pay.",
        ]
    },
    "NVIDIA": {
        "Python": [
            "How would you use Python with CUDA for GPU programming?",
            "Explain how you'd develop Python applications for NVIDIA GPUs.",
            "How would you implement Python APIs for NVIDIA's AI platform?",
            "What's your approach to Python development for deep learning on NVIDIA?",
            "How would you use Python with NVIDIA's graphics libraries?",
            "Explain how you'd optimize Python code for GPU acceleration.",
            "How would you implement Python tools for NVIDIA's gaming platform?",
            "What's your approach to Python testing for GPU applications?",
            "How would you use Python with NVIDIA's autonomous driving platform?",
            "Explain how you'd build Python services for NVIDIA's cloud gaming.",
        ],
        "Web Development": [
            "How would you design web applications for NVIDIA's GPU cloud?",
            "Explain how you'd implement real-time graphics rendering in web apps.",
            "How would you build web interfaces for NVIDIA's AI platform?",
            "What's your approach to developing for NVIDIA's gaming services?",
            "How would you design web services for GPU-accelerated computing?",
            "Explain how you'd implement WebGL applications for NVIDIA GPUs.",
            "How would you optimize web performance for graphics-intensive apps?",
            "What's your approach to building web dashboards for GPU monitoring?",
            "How would you implement streaming services for NVIDIA GeForce NOW?",
            "Explain how you'd design web interfaces for NVIDIA's developer tools.",
        ],
        "Data Structures": [
            "How would you design data structures for GPU memory optimization?",
            "Explain how you'd implement data structures for parallel processing.",
            "What data structures would you use for graphics rendering pipelines?",
            "How would you design caching for GPU computations?",
            "Explain how you'd implement data structures for neural networks.",
            "How would you handle data structures for real-time ray tracing?",
            "What's your approach to designing structures for autonomous driving data?",
            "How would you optimize data structures for GPU bandwidth?",
            "Explain how you'd design structures for game engine optimization.",
            "How would you implement efficient data transfer between CPU and GPU?",
        ],
        "Behavioral": [
            "Why do you want to work at NVIDIA?",
            "How do you align with NVIDIA's mission in AI and graphics?",
            "Tell me about a time you worked on GPU-accelerated projects.",
            "How would you contribute to NVIDIA's innovation in computing?",
            "Describe how you've optimized performance-critical systems.",
            "How do you approach learning new GPU technologies?",
            "Tell me about a time you solved a complex technical challenge.",
            "How do you stay updated with graphics and AI advancements?",
            "Describe your experience with parallel computing.",
            "How would you handle working on cutting-edge NVIDIA technologies?",
        ],
        "System Design": [
            "How would you design NVIDIA's GPU cloud infrastructure?",
            "Explain how you'd design a system for autonomous vehicle processing.",
            "How would you design NVIDIA's game streaming platform?",
            "Design a system for distributed GPU computing.",
            "How would you design NVIDIA's AI training infrastructure?",
            "Explain how you'd design a real-time ray tracing system.",
            "How would you design a system for GPU resource management?",
            "Design NVIDIA's driver update and distribution system.",
            "How would you design a system for GPU-accelerated rendering?",
            "Explain how you'd design NVIDIA's developer platform infrastructure.",
        ],
        "Machine Learning": [
            "How would you implement ML training on NVIDIA GPUs?",
            "Explain how you'd optimize deep learning models for NVIDIA hardware.",
            "How would you approach ML for autonomous driving with NVIDIA?",
            "What's your approach to distributed training on NVIDIA clusters?",
            "How would you design ML pipelines using NVIDIA's AI platform?",
            "Explain how you'd implement computer vision on NVIDIA GPUs.",
            "How would you approach ML model optimization for inference?",
            "What's your approach to using NVIDIA's TensorRT?",
            "How would you design ML systems for real-time applications?",
            "Explain how you'd implement ML for graphics and rendering.",
        ]
    },
    "Twitter (X)": {
        "Python": [
            "How would you use Python for Twitter's backend services?",
            "Explain how you'd develop Python APIs for Twitter's platform.",
            "How would you implement Python services for real-time tweet processing?",
            "What's your approach to Python development for Twitter's analytics?",
            "How would you use Python for Twitter's recommendation engine?",
            "Explain how you'd build Python tools for content moderation.",
            "How would you implement Python services for Twitter's ads platform?",
            "What's your approach to Python testing for high-traffic systems?",
            "How would you use Python for Twitter's data pipeline?",
            "Explain how you'd optimize Python for Twitter's scale.",
        ],
        "Web Development": [
            "How would you design Twitter's real-time feed?",
            "Explain how you'd implement Twitter's tweet composer.",
            "How would you build Twitter's notification system?",
            "What's your approach to developing Twitter's messaging feature?",
            "How would you design Twitter's trending topics interface?",
            "Explain how you'd implement Twitter's media upload system.",
            "How would you optimize web performance for Twitter's timeline?",
            "What's your approach to building Twitter's search interface?",
            "How would you implement Twitter's live streaming features?",
            "Explain how you'd design Twitter's profile pages.",
        ],
        "Data Structures": [
            "How would you design data structures for Twitter's timeline?",
            "Explain how you'd implement Twitter's follower graph.",
            "What data structures would you use for trending topics?",
            "How would you design caching for Twitter's feed?",
            "Explain how you'd implement data structures for Twitter's search.",
            "How would you handle data structures for millions of tweets per day?",
            "What's your approach to designing structures for Twitter's hashtags?",
            "How would you optimize data structures for real-time updates?",
            "Explain how you'd design structures for Twitter's recommendation system.",
            "How would you implement efficient tweet retrieval?",
        ],
        "Behavioral": [
            "Why do you want to work at Twitter/X?",
            "How do you align with Twitter's mission for public conversation?",
            "Tell me about a time you built something for real-time systems.",
            "How would you contribute to Twitter's culture of innovation?",
            "Describe how you've handled high-traffic applications.",
            "How do you approach content moderation challenges?",
            "Tell me about a time you optimized system performance.",
            "How do you handle working on controversial features?",
            "Describe your experience with social media platforms.",
            "How would you handle rapid changes in product direction?",
        ],
        "System Design": [
            "How would you design Twitter's tweet delivery system?",
            "Explain how you'd design Twitter's trending algorithm.",
            "How would you design Twitter's notification system?",
            "Design a system like Twitter's direct messaging.",
            "How would you design Twitter's media storage and delivery?",
            "Explain how you'd design Twitter's search infrastructure.",
            "How would you design a system for Twitter's analytics?",
            "Design Twitter's content moderation system.",
            "How would you design Twitter's advertising platform?",
            "Explain how you'd design Twitter's recommendation engine.",
        ],
        "Machine Learning": [
            "How would you design ML for Twitter's timeline ranking?",
            "Explain how you'd implement Twitter's recommendation system.",
            "How would you approach ML for content moderation?",
            "What's your approach to ML for Twitter's ad targeting?",
            "How would you design ML systems for spam detection?",
            "Explain how you'd implement sentiment analysis for tweets.",
            "How would you approach ML for trending topic prediction?",
            "What's your approach to ML for Twitter's search ranking?",
            "How would you design ML for bot detection?",
            "Explain how you'd implement ML for personalized notifications.",
        ]
    },
    "IBM": {
        "Python": [
            "How would you use Python with IBM Watson services?",
            "Explain how you'd develop Python applications for IBM Cloud.",
            "How would you implement Python APIs for IBM's AI platform?",
            "What's your approach to Python development for IBM's enterprise solutions?",
            "How would you use Python for IBM's data analytics?",
            "Explain how you'd build Python tools for IBM's quantum computing.",
            "How would you implement Python services for IBM's blockchain platform?",
            "What's your approach to Python testing for enterprise systems?",
            "How would you use Python with IBM's mainframe systems?",
            "Explain how you'd optimize Python for IBM's infrastructure.",
        ],
        "Web Development": [
            "How would you design web applications for IBM Cloud?",
            "Explain how you'd implement enterprise web services for IBM.",
            "How would you build web interfaces for IBM Watson?",
            "What's your approach to developing for IBM's enterprise clients?",
            "How would you design web services for IBM's AI platform?",
            "Explain how you'd implement security for IBM's web applications.",
            "How would you optimize web performance for enterprise scale?",
            "What's your approach to building web dashboards for IBM's analytics?",
            "How would you implement web services for IBM's blockchain?",
            "Explain how you'd design web interfaces for IBM's quantum platform.",
        ],
        "Data Structures": [
            "How would you design data structures for IBM's database systems?",
            "Explain how you'd implement data structures for Watson's AI.",
            "What data structures would you use for IBM's analytics platform?",
            "How would you design caching for IBM Cloud services?",
            "Explain how you'd implement data structures for blockchain.",
            "How would you handle data structures for enterprise-scale systems?",
            "What's your approach to designing structures for IBM's mainframes?",
            "How would you optimize data structures for quantum computing?",
            "Explain how you'd design structures for IBM's security systems.",
            "How would you implement efficient data processing for Watson?",
        ],
        "Behavioral": [
            "Why do you want to work at IBM?",
            "How do you align with IBM's focus on enterprise innovation?",
            "Tell me about a time you worked on enterprise-scale projects.",
            "How would you contribute to IBM's culture of research?",
            "Describe how you've handled complex business requirements.",
            "How do you approach learning IBM's technologies?",
            "Tell me about a time you solved a challenging technical problem.",
            "How do you handle working with enterprise clients?",
            "Describe your experience with IBM's technology stack.",
            "How would you handle working on cutting-edge IBM research?",
        ],
        "System Design": [
            "How would you design IBM's cloud infrastructure?",
            "Explain how you'd design Watson's AI processing system.",
            "How would you design IBM's blockchain platform?",
            "Design a system for IBM's enterprise data management.",
            "How would you design IBM's quantum computing platform?",
            "Explain how you'd design IBM's security infrastructure.",
            "How would you design a system for IBM's analytics platform?",
            "Design IBM's hybrid cloud architecture.",
            "How would you design IBM's mainframe modernization?",
            "Explain how you'd design IBM's AI model deployment system.",
        ],
        "Machine Learning": [
            "How would you implement ML with IBM Watson?",
            "Explain how you'd design ML pipelines for IBM Cloud.",
            "How would you approach ML for IBM's enterprise clients?",
            "What's your approach to ML model deployment on IBM infrastructure?",
            "How would you design ML systems for IBM's analytics?",
            "Explain how you'd implement NLP with Watson.",
            "How would you approach ML for IBM's security systems?",
            "What's your approach to ML for IBM's quantum computing?",
            "How would you design ML for IBM's blockchain applications?",
            "Explain how you'd implement ML for IBM's healthcare solutions.",
        ]
    },
    "Oracle": {
        "Python": [
            "How would you use Python with Oracle Database?",
            "Explain how you'd develop Python applications for Oracle Cloud.",
            "How would you implement Python APIs for Oracle's enterprise software?",
            "What's your approach to Python development for Oracle's ERP systems?",
            "How would you use Python for Oracle's data management?",
            "Explain how you'd build Python tools for Oracle's cloud infrastructure.",
            "How would you implement Python services for Oracle's applications?",
            "What's your approach to Python testing for Oracle systems?",
            "How would you use Python with Oracle's middleware?",
            "Explain how you'd optimize Python for Oracle's platform.",
        ],
        "Web Development": [
            "How would you design web applications for Oracle Cloud?",
            "Explain how you'd implement enterprise web services for Oracle.",
            "How would you build web interfaces for Oracle's ERP systems?",
            "What's your approach to developing for Oracle's enterprise clients?",
            "How would you design web services for Oracle's database?",
            "Explain how you'd implement security for Oracle's web applications.",
            "How would you optimize web performance for Oracle's platform?",
            "What's your approach to building web dashboards for Oracle Analytics?",
            "How would you implement web services for Oracle's CRM?",
            "Explain how you'd design web interfaces for Oracle's HCM.",
        ],
        "Data Structures": [
            "How would you design data structures for Oracle Database?",
            "Explain how you'd optimize data structures for Oracle's systems.",
            "What data structures would you use for Oracle's cloud services?",
            "How would you design caching for Oracle applications?",
            "Explain how you'd implement data structures for Oracle's ERP.",
            "How would you handle data structures for enterprise databases?",
            "What's your approach to designing structures for Oracle's middleware?",
            "How would you optimize data structures for Oracle's performance?",
            "Explain how you'd design structures for Oracle's analytics.",
            "How would you implement efficient query processing for Oracle?",
        ],
        "Behavioral": [
            "Why do you want to work at Oracle?",
            "How do you align with Oracle's focus on enterprise solutions?",
            "Tell me about a time you worked with database systems.",
            "How would you contribute to Oracle's culture of innovation?",
            "Describe how you've handled enterprise client requirements.",
            "How do you approach learning Oracle's technologies?",
            "Tell me about a time you optimized database performance.",
            "How do you handle working with large-scale systems?",
            "Describe your experience with Oracle's products.",
            "How would you handle working on mission-critical Oracle systems?",
        ],
        "System Design": [
            "How would you design Oracle's cloud infrastructure?",
            "Explain how you'd design Oracle Database's architecture.",
            "How would you design Oracle's ERP system?",
            "Design a system for Oracle's data warehouse.",
            "How would you design Oracle's cloud applications?",
            "Explain how you'd design Oracle's security infrastructure.",
            "How would you design a system for Oracle's analytics platform?",
            "Design Oracle's multi-tenant architecture.",
            "How would you design Oracle's backup and recovery system?",
            "Explain how you'd design Oracle's integration platform.",
        ],
        "Machine Learning": [
            "How would you implement ML with Oracle Database?",
            "Explain how you'd design ML pipelines for Oracle Cloud.",
            "How would you approach ML for Oracle's enterprise applications?",
            "What's your approach to ML model deployment on Oracle infrastructure?",
            "How would you design ML systems for Oracle's analytics?",
            "Explain how you'd implement ML for Oracle's CRM.",
            "How would you approach ML for Oracle's supply chain?",
            "What's your approach to ML for Oracle's financial systems?",
            "How would you design ML for Oracle's HCM applications?",
            "Explain how you'd implement ML for Oracle's autonomous database.",
        ]
    }
}


# Merge mass recruitment questions with main company questions
COMPANY_QUESTIONS.update(MASS_RECRUITMENT_QUESTIONS)
